### ISSUE TITLE
Report 1 RA feedback

### ISSUE THREAD

**Issue by tm545** [AguaClara/StaRSFine#4]
Hi friends,
This is a great first report, you've got great writing and I'm jealous of that. I am told to not talk about technical writing aspects but rather focus on content but I want to point out your writing is great and easy to read. Your abstract is apt and describes your subteam well. For your intro more info on the work you're doing with HorFi would be great so I can catch up on that too. I don't think there is any literature to look at now outside of Monroe deep thoughts, but probably in the future some literature on theoretical sand fluidization upflow velocity will probably come in when you have some data points of sand fluidizing. Sam you've done amazing with OnShape and your design looks like the bomb.com. Even with great designs the drawing is where you've got to actually communicate to people for how to recreate your design from scratch. People usually standardize this stuff and I've put a sample one on this issue. I'm up for another CAD day in you case need help with recreating something like this. While figure 3 is a work of social art I'd love to see the attachment of the tubes closer to the apparatus, so if Lily and Whitney could sit closer that would be great for a more detailed photo of your apparatus.

In your Experimental Apparatus Fabrication section you discuss necessary flow rate you need to model an Aguaclara plant filter but discussion on where this value comes from would also be nice. Your python code could use a boatload of comments. Your goal is to let someone who has no idea where your parameters and equations are coming from to understand your outputs. 

All in all this is a great report and you've all done incredible work. You have some minor hiccups in showing off your work but nothing that can't be fixed. I've appreciated working with you guys and I'm psyched to see where you guys take this subteam.

**Comment by tm545** [comment]
[Part Studio 1 Drawing 1.pdf](https://github.com/AguaClara/StaRSFine/files/2903800/Part.Studio.1.Drawing.1.pdf)
I forgot that drawing file sorry. Also don't think I'm a member in your repository so I can't assign you guys this issue which is cool.

**Comment by sidneylok** [comment]
Hey guys! Just wanted to add that you should have a bibliography/references section to compile all of citations for the reports and papers you referenced in your lit review and previous work sections. I didn't grade this in your first manual because I'm not sure if it was made clear enough that Fab teams need to include this, but you will be graded on it next time so be sure to include it in your next iteration! Thanks :)
